/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  ignore?: Array<string>
}
export interface Location {
  libName: string
  memberName: string
  start: number
  end: number
  filePath: string
}
export function inspectPackageUsage(workspace: string, npmNameVec: Array<string>, options?: Options | undefined | null): Promise<Array<Location>>
